<?php

require_once $_SERVER['DOCUMENT_ROOT'].'/config/functions.php';


class Query extends Functions {

    private $query , $data ,$success = "success" , $words , $error_occured = "error occured" , $error = "error";

    function __construct()
    {
        parent::__construct();
    }

    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    private function isReady () : bool {

        return isset($_POST['data']) && !empty($this->data = json_decode($_POST['data'] , true));
    }

    private  function setDetails () : bool {
        $this->query = $this->escape_string($this->data['query']);
        return true;
    }

    public function process () : bool {

        //Split the words of the array

        $this->words = $words = explode(" " , $this->query);


        foreach ($words as $word){

            if(!$this->record_exists_in_table($this->words_table_name , 'word' , $word)) {
                $this->insert_into_table($this->words_table_name , ["word" => "{$word}" , "occurrence" => 1]);
            }

            else {
                $this->executeSQL("UPDATE {$this->words_table_name} SET occurrence = occurrence + 1 WHERE word = '{$word}' ");
            }
        }


        return true;


    }



   public function Processor() : string  {

        $default_error = json_encode([$this->error => $this->error_occured , $this->success => 0]);
        if(!($this->isReady() and $this->setDetails()))return $default_error;

        if(!$this->process()) return $default_error;


        return json_encode([$this->error => "success" , $this->success => 1 , "words" => $this->words]);

   }




}

$query = new Query();
echo $query->Processor();


?>